name: 'Subgraph status action'
description: 'Github Action for checking indexing errors in the subgraphs'
author: 'akropolis.io'
branding:
  icon: 'activity'
  color: 'purple'
inputs:
  subgraph:
    required: true
    description: 'Subgraph name for check'
  version:
    required: false
    description: 'The subgraph version for check. Should be "current" or "pending"'
    default: 'current'
  fail_on_error:
    required: false
    description: 'The job will fail if passed `true` and the subgraph has indexing errors'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
