name: 'Subgraph status action'
description: 'Github Action for checking errors in the subgraphs'
author: 'akropolis.io'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
